Propagate the error to the client if the external command fails
decke/smtprelay pull request #40
Opened 2021-07-28 11:04 UTC by ca0s

This change makes the external command code return a generic 554 error to the SMTP client if the external command fails, so it knows sending failed and can retry.

2021-07-28 11:44 UTC, decke requested changes

2021-07-28 11:44 UTC, decke commented on main.go
> +			return smtpd.Error{
Please use the same single line formatting that is used already for smtpd.Error

2021-07-28 11:44 UTC, decke commented on main.go
> +				Message: "external sender error, contact your SMTP administrator",
The error message sounds very generic. Could you make it slightly more precise?
What about: "External command failed"

2021-07-28 20:18 UTC, decke commented
One last question is which SMTP status code to use in this case. 5xx codes will tell the client that the issue is permanent so do not try again. 451 sounds more appropriate and will indicate a temporary error.

2021-07-29 06:27 UTC, ca0s commented
I chose 514 because in my specific use case (my external command sends the email through an HTTP API) it is actually a permanent error: it only fails if the message body is too big.

I don't have any issues changing it to 451, as my clients will react the same.

Would you be OK if I sent another PR defining a list of status codes for external commands so smtprelay can choose the best SMTP status code? Something like:

| command status code | SMTP status code |
|-------------------------------|--------------------------|
| 0                                  | 250, mail sent        |
| -1                                | 451, temporary error, try again |
| -2                                | 554, generic permanent error |
| -3                                | 554 5.3.4, permanent error, message too big |

Kind regards, and thank you for writing this tool.

2021-07-29 08:35 UTC, decke commented
Instead of defining a list I'd prefer to leave this to the external command. So the external commands should return SMTP status codes as error codes. We won't be able to pass along nice error texts though.

2021-07-29 09:10 UTC, ca0s commented
That would be the cleanest solution. However, UNIX does not allow process return codes outside of the range [0,255]. Returning values out of that range yields unexpected codes in a standard Linux box:

```
javi@pwn ~/test/go $ cat return_fixed.go
package main

import "os"

func main() {
        os.Exit(514)
}
javi@pwn ~/test/go $ cat exec.go
package main

import (
        "fmt"
        "os/exec"
        "os"
)

func main() {
        cmd := exec.Command(os.Args[1])
        err := cmd.Run()
        exitcode := cmd.ProcessState.ExitCode()
        fmt.Printf("err: %s, exitcode: %d\n", err, exitcode)
}
javi@pwn ~/test/go $ ./exec ./return_fixed
err: exit status 2, exitcode: 2
```

Therefore, I'm afraid some mapping will be required.

2022-04-25 13:49 UTC, decke approved these changes

2022-04-25 13:52 UTC, merged

2022-04-25 13:52 UTC, decke commented
Thanks a lot for your contribution!